# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cc1da6d51752b5e505f8220a056956412ee5ce8dbc0b9e9bff6b570940700a4e1b706900f439d16b6e2d09e8c9b4957c7fd7fc5eae0140e5cb380cf3c0179d6

test:
  secret_key_base: b31fa8dd55093ca39cd997d68acba81423d51de45a7c6b5ea81ab45f9aca281086a95e7a9ecf5d3b167b0caed9b72af846b6e320cb102c5040281776a3a5a678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
